### PR TITLE
Enhancement: Custom Crawler with sub-page depth

### PR DESCRIPTION
**Pull request by Faakhir30**
I' 've created a custom iterative crawler based on sub-page depths.
Crawling is done using BFS and Depth can be specified while initialization of the crawler.

### CODE REVIEW

**Review by destrex271 — COMMENTED** [review]
Please refrain from changing the setUpClass function to setUp. Otherwise LGTM. Can you also share a file containing all the links extracted by the crawler at depth 0 and 1?

**Comment by Faakhir30** [comment]
I've renamed the methods.
Used sets instead of lists, at higher depth list is not suitable due to O(N) complexities.
Data upto depth 1 is added in crawlData.txt file

**Review by destrex271 — APPROVED** [review]
Cool, merging to main.

**Comment by destrex271** [comment]
Thanks for the contribution!

**Pull request merged**
